# Generated by Django 4.2.6 on 2023-10-10 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
